<!DOCTYPE HTML>
<html>
  <head>
    <title>Technical Documentation Demo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css" type="text/css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/railscasts.min.css" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans|Quattrocento+Sans" type="text/css">
    <link rel="stylesheet" href="style.css" type="text/css">
  </head>
  <body>
    <nav id="navbar">
      <header><span id="site-title">Using Promises</span><br/><a href="https://developer.mozilla.org/en-US/">Courtesy of MDN web docs</a></header>
      <div id="navigation-links"></div>
      <button id="menu-drawer" type="button">&#9776;</button>
    </nav>
    <main id="main-doc">
      <section class="main-section">
        <header>Introduction</header>
        <p>
          A <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise">Promise</a> is an object representing the eventual completion or failure of an asynchronous operation. Since most people are consumers of already-created promises, this guide will explain consumption of returned promises before explaining how to create them.
        </p>
        <p>
          Essentially, a promise is a returned object to which you attach callbacks, instead of passing callbacks into a function.
        </p>
        <p>
          Imagine a function, createAudioFileAsync(), which asynchronously generates a sound file given a configuration record and two callback functions, one called if the audio file is successfully created, and the other called if an error occurs.
        </p>
        <p>
          Here's some code that uses createAudioFileAsync():
        </p>
        <pre><code>function successCallback(result) {
  console.log("Audio file ready at URL: " + result);
}

function failureCallback(error) {
  console.log("Error generating audio file: " + error);
}

createAudioFileAsync(audioSettings, successCallback, failureCallback);</code></pre>
        <p>
          â€¦modern functions return a promise you can attach your callbacks to instead:
        </p>
        <p>
          If createAudioFileAsync() were rewritten to return a promise, using it could be as simple as this:
        </p>
        <pre><code>createAudioFileAsync(audioSettings).then(successCallback, failureCallback);</code></pre>
        <p>
          That's shorthand for:
        </p>
        <pre><code>const promise = createAudioFileAsync(audioSettings); 
promise.then(successCallback, failureCallback);</code></pre>
        <p>
          We call this an asynchronous function call. This convention has several advantages. We will explore each one.
        </p>
      </section>
      <section class="main-section">
        <header>Guarantees</header>
        <p>
          Unlike old-style passed-in callbacks, a promise comes with some guarantees
        </p>
        <ul>
          <li>Callbacks will never be called <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop#Run-to-completion">before the completion of the current run</a> of the JavaScript event loop.</li>
          <li>Callbacks added with <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then">then()</a> even after the success or failure of the asynchronous operation, will be called, as above.</li>
          <li>Multiple callbacks may be added by calling <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then">then()</a> several times. Each callback is executed one after another, in the order in which they were inserted.</li>
          <p>
            One of the great things about using promises is chaining.
          </p>
        </ul>
      </section>
      <section class="main-section">
        <header>Chaining</header>
        <p>
          A common need is to execute two or more asynchronous operations back to back, where each subsequent operation starts when the previous operation succeeds, with the result from the previous step. We accomplish this by creating a promise chain.
        </p>
        <p>
          Here's the magic: the then() function returns a new promise, different from the original:
        </p>
        <pre><code>const promise = doSomething();
const promise2 = promise.then(successCallback, failureCallback);</code></pre>
        <p>
          or
        </p>
        <pre><code>const promise2 = doSomething().then(successCallback, failureCallback);</code></pre>
        <p>
          This second promise represents the completion not just of doSomething(), but also of the successCallback or failureCallback you passed in, which can be other asynchronous functions returning a promise. When that's the case, any callbacks added to promise2 get queued behind the promise returned by either successCallback or failureCallback.

        </p>
        <p>
          Basically, each promise represents the completion of another asynchronous step in the chain.
        </p>
        <p>
          In the old days, doing several asynchronous operations in a row would lead to the classic callback pyramid of doom:
        </p>   
        <pre><code>doSomething(function(result) {
  doSomethingElse(result, function(newResult) {
    doThirdThing(newResult, function(finalResult) {
      console.log('Got the final result: ' + finalResult);
    }, failureCallback);
  }, failureCallback);
}, failureCallback);</code></pre>
        <p>
          With modern functions, we attach our callbacks to the returned promises instead, forming a promise chain:
        </p>
        <pre><code>doSomething().then(function(result) {
  return doSomethingElse(result);
})
.then(function(newResult) {
  return doThirdThing(newResult);
})
.then(function(finalResult) {
  console.log('Got the final result: ' + finalResult);
})
.catch(failureCallback);</code></pre>
        <p>
          The arguments to then are optional, and catch(failureCallback) is short for then(null, failureCallback). You might see this expressed with <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions">arrow functions</a> instead:
        </p>
        <pre><code>doSomething()
.then(result => doSomethingElse(result))
.then(newResult => doThirdThing(newResult))
.then(finalResult => {
  console.log(`Got the final result: ${finalResult}`);
})
.catch(failureCallback);</code></pre>
        <p>
          Important: Always return results, otherwise callbacks won't catch the result of a previous promise.
        </p>
      </section>
      <section class="main-section">
        <header>Chaining after a catch</header>
        <p>It's possible to chain after a failure, i.e. a catch, which is useful to accomplish new actions even after an action failed in the chain. Read the following example:</p>

        <pre><code>new Promise((resolve, reject) => {
  console.log('Initial');
  resolve();
})
.then(() => {
  throw new Error('Something failed');
  console.log('Do this');
})
.catch(() => {
  console.log('Do that');
})
.then(() => {
  console.log('Do this, no matter what happened before');
});</code></pre>
        <p>
          This will output the following text:
        </p>
        <pre><code class="javascript">// Initial
// Do that
// Do this, no matter what happened before</code></pre>
        <p>
          Note that the text "Do this" is not output because the "Something failed" error caused a rejection.
        </p>
      </section>
      <section class="main-section">
        <header>Error propagation</header>
        <p>
          You might recall seeing failureCallback three times in the pyramid of doom earlier, compared to only once at the end of the promise chain:
        </p>
        <pre><code>doSomething()
.then(result => doSomethingElse(result))
.then(newResult => doThirdThing(newResult))
.then(finalResult => console.log(`Got the final result: ${finalResult}`))
.catch(failureCallback);</code></pre>
        <p>
          Basically, a promise chain stops if there's an exception, looking down the chain for catch handlers instead. This is very much modeled after how synchronous code works:
        </p>
        <pre><code>try {
  const result = syncDoSomething();
  const newResult = syncDoSomethingElse(result);
  const finalResult = syncDoThirdThing(newResult);
  console.log(`Got the final result: ${finalResult}`);
} catch(error) {
  failureCallback(error);
}</code></pre>
        <p>
          This symmetry with synchronous code culminates in the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function">async/await</a> syntactic sugar in ECMAScript 2017:
        </p>
        <pre><code>async function foo() {
  try {
    const result = await doSomething();
    const newResult = await doSomethingElse(result);
    const finalResult = await doThirdThing(newResult);
    console.log(`Got the final result: ${finalResult}`);
  } catch(error) {
    failureCallback(error);
  }
}</code></pre>
        <p>
          It builds on promises, e.g. doSomething() is the same function as before. You can read more about the syntax <a href="https://developers.google.com/web/fundamentals/getting-started/primers/async-functions">here</a>.
        </p>
        <p>
          Promises solve a fundamental flaw with the callback pyramid of doom, by catching all errors, even thrown exceptions and programming errors. This is essential for functional composition of asynchronous operations.
        </p>
      </section>
      <section class="main-section">
        <header>Creating a Promise around an old callback API</header>
        <p>
          A <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise">Promise</a> can be created from scratch using its constructor. This should be needed only to wrap old APIs.

        </p>
        <p>
          In an ideal world, all asynchronous functions would already return promises. Alas, some APIs still expect success and/or failure callbacks to be passed in the old way. The quintessential example is the <a href="https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout">setTimeout()</a> function:
        </p>
        <pre><code>setTimeout(() => saySomething("10 seconds passed"), 10000);</code></pre>
        <p>
          Mixing old-style callbacks and promises is problematic. If saySomething() fails or contains a programming error, nothing catches it.
        </p>
        <p>
          Luckily we can wrap it in a promise. Best practice is to wrap problematic functions at the lowest possible level, and then never call them directly again:
        </p>
        <pre><code>const wait = ms => new Promise(resolve => setTimeout(resolve, ms));

wait(10000).then(() => saySomething("10 seconds")).catch(failureCallback);</code></pre>
        <p>
          Basically, the promise constructor takes an executor function that lets us resolve or reject a promise manually. Since setTimeout() doesn't really fail, we left out reject in this case.
        </p>
      </section>
      <section class="main-section">
        <header>Composition</header>
        <p>
          <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve">Promise.resolve()</a> and <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject">Promise.reject()</a> are shortcuts to manually create an already resolved or rejected promise respectively. This can be useful at times.
        </p>
        <p>
          <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all">Promise.all()</a> and <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race">Promise.race()</a> are two composition tools for running asynchronous operations in parallel.
        </p>
        <p>
          Sequential composition is possible using some clever JavaScript:
        </p>
        <pre><code>[func1, func2].reduce((p, f) => p.then(f), Promise.resolve());</code></pre>
        <p>
          Basically, we reduce an array of asynchronous functions down to a promise chain equivalent to: Promise.resolve().then(func1).then(func2);
        </p>
        <p>
          This can also be done with a reusable compose function, which is common in functional programming:
        </p>
        <pre><code>const applyAsync = (acc,val) => acc.then(val);
const composeAsync = (...funcs) => x => funcs.reduce(applyAsync, Promise.resolve(x));</code></pre>
        <p>
          The composeAsync() function will accept any number of functions as arguments, and will return a new function that accepts an initial value to be passed through the composition pipeline. This is beneficial because any or all of the functions may be either asynchronous or synchronous, and they are guaranteed to be executed in the correct order:
        </p>
        <pre><code>const transformData = composeAsync(func1, asyncFunc1, asyncFunc2, func2);
transformData(data);</code></pre>
        <p>
          In ECMAScript 2017, sequential composition can be done more simply with async/await:
        </p>
        <pre><code>for (const f of [func1, func2]) {
  await f();
}</code></pre>
      </section>
      <section class="main-section">
        <header>Timing</header>
        <p>
          To avoid surprises, functions passed to <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then">then()</a> will never be called synchronously, even with an already-resolved promise:
        </p>
        <pre><code>Promise.resolve().then(() => console.log(2));
console.log(1); // 1, 2</code></pre>
        <p>
          Instead of running immediately, the passed-in function is put on a microtask queue, which means it runs later when the queue is emptied at the end of the current run of the JavaScript event loop, i.e. pretty soon:
        </p>
        <pre><code>const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
wait().then(() => console.log(4));
Promise.resolve().then(() => console.log(2)).then(() => console.log(3));
console.log(1); // 1, 2, 3, 4</code></pre>
      </section>
      <section class="main-section">
        <header>Nesting</header>

        <p> 
          Simple promise chains are best kept flat without nesting, as nesting can be a result of careless composition. See <a href="#Common_mistakes">common mistakes</a>.
        </p>
        <p>
          Nesting is a control structure to limit the scope of catch statements. Specifically, a nested catch only catches failures in its scope and below, not errors higher up in the chain outside the nested scope. When used correctly, this gives greater precision in error recovery:
        </p>
        <pre><code>doSomethingCritical()
.then(result => doSomethindOptional()
.then(optionalResult => doSomethingExtraNice(optionalResult))
.catch(e => {})) // Ignore if optional stuff fails; proceed.
.then(() => moreCriticalStuff())
.catch(e => console.log("Critical failure: " + e.message));</code></pre>
        <p>
          Note that the optional steps here are nested, not from the indentation, but from the precarious placement of the outer ( and ) around them.

        </p>
        <p>  
          The inner neutralizing catch statement only catches failures from doSomethingOptional() and doSomethingExtraNice(), after which the code resumes with moreCriticalStuff(). Importantly, if doSomethingCritical() fails, its error is caught by the final (outer) catch only.
        </p>
      </section>
      <section class="main-section">
        <header>Common mistakes</header>
        <p>
          Here are some common mistakes to watch out for when composing promise chains. Several of these mistakes manifest in the following example:
        </p>
        <pre><code>// Bad example! Spot 3 mistakes!

doSomething().then(function(result) {
  doSomethingElse(result) // Forgot to return promise from inner chain + unnecessary nesting
  .then(newResult => doThirdThing(newResult));
}).then(() => doFourthThing());
// Forgot to terminate chain with a catch!</code></pre>
        <p>
          The first mistake is to not chain things together properly. This happens when we create a new promise but forget to return it. As a consequence, the chain is broken, or rather, we have two independent chains racing. This means doFourthThing() won't wait for   doSomethingElse() or doThirdThing() to finish, and will run in parallel with them, likely unintended. Separate chains also have separate error handling, leading to uncaught errors.
        </p>
        <p>
          The second mistake is to nest unnecessarily, enabling the first mistake. Nesting also limits the scope of inner error handlers, whichâ€”if unintendedâ€”can lead to uncaught errors. A variant of this is the <a href="https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it">promise constructor anti-pattern</a>, which combines redundant use of the promise constructor with nesting.
        </p>
        <p>
          The third mistake is forgetting to terminate chains with catch. Unterminated promise chains lead to uncaught promise rejections in most browsers.

        </p>
        <p>
          A good rule-of-thumb is to always either return or terminate promise chains, and as soon as you get a new promise, return it, to flatten things:
        </p>
        <pre><code>doSomething()
.then(function(result) {
  return doSomethingElse(result);
})
.then(newResult => doThirdThing(newResult))
.then(() => doFourthThing());
.catch(error => console.log(error));</code></pre>
        <p>        
          Note that () => x is short for () => { return x; }.
        </p>
        <p>
          Now we have a single deterministic chain with proper error handling.
        </p>
        <p>
          Using <a href="async/await">async/await</a> addresses most, if not all of these problemsâ€”the tradeoff being that the most common mistake with that syntax is forgetting the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function">await</a> keyword.
        </p>
      </section>
      <section class="main-section">
        <header>See also</header>
        <ul>
          <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then">Promise.then()</a></li>
          <li><a href="http://promisesaplus.com/">Promises/A+ specification</a></li>
          <li><a href="https://medium.com/@ramsunvtech/promises-of-promise-part-1-53f769245a53">Venkatraman.R - JS Promise (Part 1, Basics)</a></li>
          <li><a href="https://medium.com/@ramsunvtech/js-promise-part-2-q-js-when-js-and-rsvp-js-af596232525c#.dzlqh6ski">Venkatraman.R - JS Promise (Part 2 - Using Q.js, When.js and RSVP.js)</a></li>
          <li><a href="https://tech.io/playgrounds/11107/tools-for-promises-unittesting/introduction">Venkatraman.R - Tools for Promises Unit Testing</a></li>
          <li><a href="http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html">Nolan Lawson: We have a problem with promises â€” Common mistakes with promises</a></li>
        </ul>
      </section>
    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script src="script.js"></script>
  </body>
</html>